# Generated by Django 5.2.2 on 2025-06-10 09:47

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pharma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_pharma", models.CharField(default="Pharma", max_length=35)),
                ("code_pharma", models.CharField(default="PH000", max_length=8)),
                ("loc_street", models.CharField(default="Pharma", max_length=15)),
                ("loc_quarter", models.CharField(default="Pharma", max_length=15)),
                ("loc_commune", models.CharField(default="Pharma", max_length=15)),
                ("loc_Province", models.CharField(default="Pharma", max_length=15)),
                ("loc_country", models.CharField(default="Pharma", max_length=15)),
                ("ranking", models.IntegerField(default=0)),
                ("joined_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_connected",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_med", models.CharField(default="med", max_length=75)),
                ("score", models.IntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pharma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.pharma"
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
