# Generated by Django 5.2.4 on 2025-07-21 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pharma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_pharma",
                    models.CharField(default="Pharma", max_length=35, unique=True),
                ),
                ("code_pharma", models.IntegerField(default=1000)),
                ("tel", models.IntegerField(default=0)),
                ("loc_street", models.CharField(default="13", max_length=15)),
                ("loc_quarter", models.CharField(default="Kamenge", max_length=15)),
                ("loc_commune", models.CharField(default="Ntahangwa", max_length=15)),
                ("loc_Province", models.CharField(default="Bujumbura", max_length=15)),
                ("loc_country", models.CharField(default="Burundi", max_length=15)),
                ("score", models.IntegerField(default=0)),
                ("joined_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_connected",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pharmacie",
            },
        ),
        migrations.CreateModel(
            name="MedCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_med", models.CharField(default="med", max_length=75)),
                ("qte", models.IntegerField(default=0)),
                ("price", models.IntegerField(default=0)),
                ("date_per", models.CharField(default="2028", max_length=35)),
                ("sync_code", models.IntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.pharma"
                    ),
                ),
            ],
        ),
    ]
